library(tidyverse)
library(zoo)
library(ggpubr)
library(gridExtra)
library(stringr)

###
###Import/formatting functions
###


generate_tax_table = function(tax_report_tsv) {
  ###create a table from a kraken2 taxonomy report whose location is specified at tax_report_tsv
  require(tidyverse)
  colnames = c("percentOfReads", "nodeAndChildren", "nodeOnly", "taxLevel", "taxID", "name")
  coltypes = "diicff"
  tax_report = read_tsv(tax_report_tsv, col_names = colnames, col_types = coltypes)
  generate_sublevels = function(char, range = 1:9){
    out = c()
    for(x in char) {
      out = c(out, x, paste(x, range, sep=""))
    }
    return(out)
  }
  all_tax_levels = generate_sublevels(c("U", "R", "D", "P", "C", "O", "F", "G",
                                        "S"))
  relevant_tax_levels = unique(tax_report$taxLevel)
  selected_tax_levels = all_tax_levels[which(all_tax_levels %in% 
                                               relevant_tax_levels)]
  tax_table = pivot_wider(tax_report, names_from = taxLevel, 
                          values_from = name) %>%
    select("percentOfReads", "nodeAndChildren", "nodeOnly", "taxID", 
           selected_tax_levels)
  return(tax_table)
}

fill_tax_NAs = function(tax_table) {
  ###Fill in blank spaces with lowest applicable taxa IDs. tax_table is generated by generate_tax_table()
  require(dplyr)
  require(zoo)
  taxa = select(tax_table, "U":last_col())
  taxa = tibble(data.frame(lapply(taxa, as.character), stringsAsFactors = FALSE))
  taxa[1,] = "unclassified"
  for(r in 2:nrow(taxa)) {
    hrow = taxa[r,]
    for(c in 1:(ncol(hrow)-1)){
      if(!is.na(hrow[,c]) && is.na(hrow[,(c+1)])) {
        hrow[,(c+1):ncol(hrow)] = paste("unidentified (", colnames(hrow[,c]), ": ", hrow[1,c], ")", sep="")
      }
    }
    taxa[r,] = hrow
  }
  taxa = na.locf(taxa)
  out = cbind(select(tax_table, "percentOfReads":"taxID"), taxa)
  out$RA <- ((out$nodeOnly)/(sum(out$nodeOnly)))
  return(out)
}

generate_complete_table <- function(src1, src2, SampleID1, SampleID2){
  ###Generate a table from two kraken2 taxonomy report files (e.g. DNA and RNA outputs)
  ###Files located at src1 and src2
  ###SampleID column will be created so both files can be combined into a single table, using user-specified IDs. 
  tax1 <- generate_tax_table(src1)
  tax2 <- generate_tax_table(src2)
  
  filled1 <- fill_tax_NAs(tax1)
  filled2 <- fill_tax_NAs(tax2)
  
  filled1$SampleID <- SampleID1
  filled2$SampleID <- SampleID2
  
  complete <- bind_rows(filled1, filled2)
}



###
###Plotting Funftions
###

plot_subset <- function(formatted_tax_table, yunit, filter_level, filter_id, fill_level) {
  ###Plot a particular taxon specified from complete table
  require(tidyverse)
  to_plot <- filter(formatted_tax_table, !!as.name(filter_level) == filter_id) %>%
    filter(nodeOnly != 0)
  plt <- ggplot(to_plot, aes(y = !!as.name(yunit), fill = !!as.name(fill_level), x = SampleID)) +
    geom_bar(position = "stack", stat = "identity") +
    xlab("") +
    theme_bw()
  if(yunit == "nodeOnly") {
    plt <- plt + ylab("Number of reads")
  } else if(yunit == "RA") {
    plt <- plt + ylab("Portion of reads")
  } else {
    plt <- plt + ylab(yunit)
  }
  return(plt)
}

plot4 <- function(formatted_tax_table1, formatted_tax_table2, filter_level, filter_id, fill_level, fill_label, title, height = 8.5, widths = c(8,2)) {
  ###Create 4 plots side-by-side, for comparing absolute and relative abundance (based on read counts), as well as confidence levels
  require(tidyverse)
  require(ggpubr)
  require(gridExtra)
  require(stringr)
  to_plot_50 <- filter(formatted_tax_table1, !!as.name(filter_level) == filter_id) %>%
    filter(nodeOnly != 0)
  to_plot_00 <- filter(formatted_tax_table2, !!as.name(filter_level) == filter_id) %>%
    filter(nodeOnly != 0)
  all_data <- bind_rows(to_plot_50, to_plot_00)
  limits <- levels(as.factor(all_data[,fill_level]))
  
  p <- ggplot() + 
    geom_point(data=all_data, aes(x=SampleID, y=RA, color=!!as.name(fill_level)), shape=15, size=5) + 
    guides(color=guide_legend(title=fill_label)) +
    labs(color = fill_label) +
    scale_color_discrete(limits = limits, labels = ~ stringr::str_wrap(.x, width = 30)) +
    theme_bw() +
    theme(legend.spacing.y = unit(0.25, "cm")) +
    guides(color=guide_legend(byrow = TRUE))
  
  Abs50 <- plot_subset(formatted_tax_table1, "nodeOnly", filter_level, filter_id, fill_level) + 
    ggtitle(" ") + 
    labs(fill = fill_label) +
    scale_fill_discrete(limits = limits)
  
  Rel50 <- plot_subset(formatted_tax_table1, "RA", filter_level, filter_id, fill_level) + 
    ggtitle(" ") + 
    labs(fill = fill_label) +
    scale_fill_discrete(limits = limits)
  
  both50 <- ggarrange(Abs50, Rel50, ncol = 2, nrow = 1, common.legend = TRUE, legend = "none") %>%
    annotate_figure(fig.lab = "        Minimum confidence = 0.5", fig.lab.pos = "top.left", fig.lab.size = 14)
  
  
  Abs00 <- plot_subset(formatted_tax_table2, "nodeOnly", filter_level, filter_id, fill_level) + 
    ggtitle(" ") + 
    labs(fill = fill_label) +
    scale_fill_discrete(limits = limits)
  
  Rel00 <- plot_subset(formatted_tax_table2, "RA", filter_level, filter_id, fill_level) + 
    ggtitle(" ") + 
    labs(fill = fill_label) +
    scale_fill_discrete(limits = limits)
  
  both00 <- ggarrange(Abs00, Rel00, ncol = 2, nrow = 1, common.legend = TRUE, legend = "none") %>%
    annotate_figure(fig.lab = "        No miminum confidence", fig.lab.pos = "top.left", fig.lab.size = 14)
  
  fig <- ggarrange(both50, both00, ncol = 1, nrow = 2, common.legend = TRUE, legend = "none")
  leg <- get_legend(p, position = NULL)
  fig <- grid.arrange(fig, as_ggplot(leg), ncol = 2, heights = c(height), widths = widths)
  annotate_figure(fig, top = text_grob(title, size = 18))
}


plotDnaRna <- function(formatted_tax_table1, formatted_tax_table2, filter_level, filter_id, fill_level, fill_label, title, height = 8.5, widths = c(8,2)) {
  ###Plot relative and absolute abundance for both DNA + RNA
  require(tidyverse)
  require(ggpubr)
  require(gridExtra)
  require(stringr)
  to_plot_DNA <- filter(formatted_tax_table1, !!as.name(filter_level) == filter_id) %>%
    filter(nodeOnly != 0)
  to_plot_RNA <- filter(formatted_tax_table2, !!as.name(filter_level) == filter_id) %>%
    filter(nodeOnly != 0)
  all_data <- bind_rows(to_plot_DNA, to_plot_RNA)
  limits <- levels(as.factor(all_data[,fill_level]))
  
  p <- ggplot() + 
    geom_point(data=all_data, aes(x=SampleID, y=RA, color=!!as.name(fill_level)), shape=15, size=5) + 
    guides(color=guide_legend(title=fill_label)) +
    labs(color = fill_label) +
    scale_color_discrete(limits = limits, labels = ~ stringr::str_wrap(.x, width = 30)) +
    theme_bw() +
    theme(legend.spacing.y = unit(0.25, "cm")) +
    guides(color=guide_legend(byrow = TRUE))
  
  AbsDNA <- plot_subset(formatted_tax_table1, "nodeOnly", filter_level, filter_id, fill_level) + 
    ggtitle(" ") + 
    labs(fill = fill_label) +
    scale_fill_discrete(limits = limits)
  
  RelDNA <- plot_subset(formatted_tax_table1, "RA", filter_level, filter_id, fill_level) + 
    ggtitle(" ") + 
    labs(fill = fill_label) +
    scale_fill_discrete(limits = limits)
  
  bothDNA <- ggarrange(AbsDNA, RelDNA, ncol = 2, nrow = 1, common.legend = TRUE, legend = "none") %>%
    annotate_figure(fig.lab = "        DNA", fig.lab.pos = "top.left", fig.lab.size = 14)
  
  
  AbsRNA <- plot_subset(formatted_tax_table2, "nodeOnly", filter_level, filter_id, fill_level) + 
    ggtitle(" ") + 
    labs(fill = fill_label) +
    scale_fill_discrete(limits = limits)
  
  RelRNA <- plot_subset(formatted_tax_table2, "RA", filter_level, filter_id, fill_level) + 
    ggtitle(" ") + 
    labs(fill = fill_label) +
    scale_fill_discrete(limits = limits)
  
  bothRNA <- ggarrange(AbsRNA, RelRNA, ncol = 2, nrow = 1, common.legend = TRUE, legend = "none") %>%
    annotate_figure(fig.lab = "        RNA", fig.lab.pos = "top.left", fig.lab.size = 14)
  
  fig <- ggarrange(bothDNA, bothRNA, ncol = 1, nrow = 2, common.legend = TRUE, legend = "none")
  leg <- get_legend(p, position = NULL)
  fig <- grid.arrange(fig, as_ggplot(leg), ncol = 2, heights = c(height), widths = widths)
  annotate_figure(fig, top = text_grob(title, size = 18))
}


