#Main dir that contains all targeted panel results
topdir <- "/projects/bios_microbe/cowen20/targeted_panels/"


#VSP Subdir
setwd(paste0(topdir, "vsp_panels/raw_fastqs/fastp_out_no_dedup/kraken2_out/",
             "k2_nt_20240530/rrna_labeled/"))

#Find all kraken 2 reports in current dir
vsp_file_list <- list.files(pattern = "*report.tsv")

#Define function to split content of SampleID column into more useful info
parse_sample_ids <- function(taxtable) {
  separate(taxtable,
           col = SampleID,
           into = c("QCSeqID", "LIMS_ID", "Treatment",
                    NA, NA, NA, NA, NA, 
                    "ribosomal", NA ), 
           sep="(-|_)")
}


#Define function to assign locations based on sample IDs
parse_locations <- function(taxtable) {
  mutate(taxtable, site = str_replace_all(
    LIMS_ID,
    c(
      "(36397|38156|41596|34970)" = "OBrien", #regex for any one of the given strings
      "(32976|32989|20040|22015)" = "OHare"
    )
  )
  )
}

fill_tax_NAs2 = function(tax_table) {
  ###Fill in blank spaces with lowest applicable taxa IDs. tax_table is generated by generate_tax_table()
  require(dplyr)
  require(zoo)
  taxa = tax_table %>%
    select("U":last_col()) %>%
    mutate(across(everything(), as.character))
  col_names <- colnames(taxa)
  
  fill_missing <- function(row) {
    for (i in seq_len(length(row) - 1)) {
      if (!is.na(row[i]) && is.na(row[i + 1])) {
        row[(i + 1):length(row)] <- paste0("unidentified (", col_names[i], ": ", row[i], ")")
        break
      }
    }
    return(row)
  }
  
  taxa <- t(apply(taxa, 1, function(row) fill_missing(row)))
  taxa[1, ] <- "unclassified"
  taxa <- na.locf(taxa)
  
  out <- bind_cols(select(tax_table, "percentOfReads":"taxID"), taxa)
  out <- mutate(out, RA = nodeOnly / sum(nodeOnly))
  
  return(out)
}

placeholder_list <- vector("list", length = length(vsp_file_list))
for (k2t in seq_len(length(vsp_file_list))) {
  x <- generate_tax_table(paste0(vsp_file_list[k2t])) %>%
    fill_tax_NAs2() %>%
    mutate(SampleID = vsp_file_list[[k2t]])
  placeholder_list[[k2t]] <- x
  print(k2t)
}
rm(x)

test_ <- fill_tax_NAs2(placeholder_list[[1]])
test2_ <- fill_tax_NAs(placeholder_list[[1]])


common_cols <- names(test_)
diffs <- sapply(common_cols, function(col) !identical(test_[[col]], test2_[[col]]))
names(diffs)[diffs]

dif_matrix <- test_ != test2_

#read_coverage_vs_ref_coverage_rpip_vs_rpip <- bind_rows(placeholder_list)

#read_coverage_vs_ref_coverage_rpip_vs_rpip <- add_taxonomy(read_coverage_vs_ref_coverage_rpip_vs_rpip)
#read_coverage_vs_ref_coverage_rpip_vs_rpip$Enrichment <- "RPIP"

#Untargeted vs RPIP:
#if(exists("read_coverage_vs_ref_coverage_unt_vs_rpip")){
#  rm(read_coverage_vs_ref_coverage_unt_vs_rpip)
#}

#file_list <- list.files(path = unt_vs_rpip_dir, pattern = "*.tsv")
#placeholder_list <- vector("list", length = length(file_list))
#for (cvt in seq_len(length(file_list))) {
#  x = import_coverage_of_rpip_ref(paste0(unt_vs_rpip_dir, file_list[cvt]))
#  placeholder_list[[cvt]] <- x
#}

#read_coverage_vs_ref_coverage_unt_vs_rpip <- bind_rows(placeholder_list)

#read_coverage_vs_ref_coverage_unt_vs_rpip <- add_taxonomy(read_coverage_vs_ref_coverage_unt_vs_rpip)
#read_coverage_vs_ref_coverage_unt_vs_rpip$Enrichment <- "None"

#read_coverage_vs_ref_coverage_both_vs_rpip <- bind_rows(
#  read_coverage_vs_ref_coverage_rpip_vs_rpip,
#  read_coverage_vs_ref_coverage_unt_vs_rpip
#)

#rm(read_coverage_vs_ref_coverage_rpip_vs_rpip, read_coverage_vs_ref_coverage_unt_vs_rpip)